# serverless.yml

service: serverless-app

custom:
  tableName: 'tb_users'
  minionTableName: 'tb_minions'
  carrinhoTableName: 'tb_carrinhos'

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  
  environment:
    USERS_TABLE: ${self:custom.tableName}
    MINIONS_TABLE: ${self:custom.minionTableName}
    CARRINHOS_TABLE: ${self:custom.carrinhoTableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'



plugins:
  - serverless-offline        